main: de.raidcraft.worldcontrol.WorldControlPlugin
name: WorldControl
version: ${project.version}#${build.number}
description: World regeneration.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]